appHome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='home')
]

appHomePage/urls.py
from django.urls import path
from . import views

app_name = 'appHomePage'

urlpatterns = [
    path('', views.home, name='home')
]

appNews/urls.py
from django.urls import path
from . import views

app_name = "appNews"

urlpatterns = [
    path('', views.home, name='home'),
]

appPrice/urls.py
from django.urls import path
from . import views

app_name = 'appPrice'

urlpatterns = [
    path('', views.home, name='home'),
]

appPttParser/urls.py
from django.urls import path
from . import views

app_name = 'appPttParser'

urlpatterns = [
    path('', views.home, name='home'),
    path('show_img', views.show_img, name='show-img'),
]

ml101/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appHomePage.urls', namespace='appHomePage')),
    path('PttParser/', include('appPttParser.urls', namespace='appPttParser')),
    path('Price/', include('appPrice.urls', namespace='appPrice')),
    path('News/', include('appNews.urls', namespace='appNews')),
#    re_path('.*', include('appHomePage.urls', namespace='appHomePag')),
]

appHomePage/models.py
from django.db import models

# Create your models here.

appNews/models.py
from django.db import models

# Create your models here.

appPrice/models.py
from django.db import models

# Create your models here.

appPttParser/models.py
from django.db import models

# Create your models here.

appHome/views.py
from django.shortcuts import render

# Create your views here.

def home(request):

    return render(request, 'appHome/home.html')

appHomePage/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    previous = ""

    return render(request, 'appHomePage/home.html', locals())

appNews/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup

import requests

# Create your views here.

def home(request):
    news_list = []
    headers = {
        "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
    }

    # Apple Daily News
    url_Apple = "https://tw.appledaily.com/recommend/realtime"
    res_Apple = requests.get(url_Apple)
    soup_Apple = BeautifulSoup(res_Apple.text, "html.parser")
    news_Apple = soup_Apple.select(".item")
    for apple in news_Apple:
        # new = (title, url, img, source)
        news = (apple.find("img").get("alt"), apple.find("a").get("href"), apple.find("img").get("data-src"), "蘋果日報")
        # Avoid some news don't have domain in front of href
        if str(apple.find("a").get("href"))[0:4] == "http":
            news_list.append(news)

    # Yahoo News
    url_Yahoo = "https://tw.news.yahoo.com/"
    res_Yahoo = requests.get(url_Yahoo, headers=headers)
    soup_Yahoo = BeautifulSoup(res_Yahoo.text, "html.parser")
    news_Yahoo = soup_Yahoo.find_all("img")
    atag_Yahoo = soup_Yahoo.find_all("a")
    for yahoo in news_Yahoo:
        if str(yahoo.get("style"))[0:17] == "object-fit:cover;" and str(yahoo.get("alt"))[0] == "/":
            if str(yahoo.get("style")) != "object-fit:cover;":
                start = str(yahoo.get("style")).find("http")
                end = str(yahoo.get("style")).find(");")
                img = str(yahoo.get("style"))[start:end]
            else:
                img = str(yahoo.get("src"))

            for atag in atag_Yahoo:
                if atag.get("href") == yahoo.get("alt"):
                    title = atag.text
                    break

            # new = (title, url, img, source)
            news = (title, "https://tw.news.yahoo.com" + yahoo.get("alt"), img, "Yahoo新聞")
            news_list.append(news)

    return render(request, 'appNews/home.html', locals())

appPrice/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup

import requests, json

# Create your views here.

def home(request):

    if request.method == "POST":
        item_name = request.POST.get("name")
        item_list = []
        count = 5   # Change how many items want search

        # PChome
        url_Pchome = "https://ecshweb.pchome.com.tw/search/v3.3/all/results?q=" + item_name + "&page=1&sort=rnk/dc"
        res_Pchome = requests.get(url_Pchome)
        data_Pchome = json.loads(res_Pchome.text)
        if data_Pchome["totalRows"] != 0:
            item_Pchome = data_Pchome["prods"]
            for i in range(count if data_Pchome["totalRows"] >= count else data_Pchome["totalRows"]):
                # item = (name, link, price, img, shop)
                item = (
                    item_Pchome[i].get("name"),
                    "https://24h.pchome.com.tw/prod/" + item_Pchome[i].get("Id"),
                    "$" + str(item_Pchome[i].get("price")),
                    "https://a.ecimg.tw" + item_Pchome[i].get("picS"),
                    "PChome24h購物"
                )
                item_list.append(item)

        # Yahoo
        url_Yahoo = "https://tw.search.buy.yahoo.com/search/shopping/product?p=" + item_name + "&qt=product&cid=0&clv=0&cid_path="
        res_Yahoo = requests.post(url_Yahoo)
        soup = BeautifulSoup(res_Yahoo.text, "html.parser")
        data_Yahoo = soup.select(".BaseGridItem__content___3LORP")
        if len(data_Yahoo) != 0:
            for i in range(count if len(data_Yahoo) >= count else len(data_Yahoo)):
                # item = (name, link, price, img, shop)
                item = (
                    data_Yahoo[i].text.split("$")[0],
                    data_Yahoo[i].get("href"),
                    "$" + data_Yahoo[i].text.split("$")[1] if not "折" in data_Yahoo[i].text else "$" + data_Yahoo[i].text.split("$")[1].split("折")[0],
                    data_Yahoo[i].find_all("div")[0].get("style").split("(")[1].split(")")[0],
                    "Yahoo購物中心"
                )
                item_list.append(item)

        return render(request, 'appPrice/result.html', locals())

    return render(request, 'appPrice/home.html')

appPttParser/views.py
from django.shortcuts import render, redirect
from bs4 import BeautifulSoup

import requests

# Create your views here.

def home(request):

    if request.method == "POST":
        url = request.POST.get("href")

        # Check url is under ptt domain
        if url[0:22] != "https://www.ptt.cc/bbs":
            url = "https://www.ptt.cc/bbs/" + url + "/index.html"

        if "index" in url:
            tag = 0
        else:
            tag = 1

        html = requests.get(url, cookies={"over18":"1"})
        html.decoding = "utf-8"

        if html.status_code != 200:
            message = "輸入錯誤或查無此看板、文章，請重新輸入。"

            return render(request, 'appPttParser/home.html', {"message":message})

        soup = BeautifulSoup(html.text, 'html.parser')
        soup_list = soup.find_all("a")
        image_list = []

        if tag == 0:
            for atag in soup_list:
                if "M." in str(atag.get("href")):
                    html = requests.get("https://www.ptt.cc" + str(atag.get("href")), cookies={"over18":"1"})
                    html.decoding = "utf-8"
                    soup = BeautifulSoup(html.text, "html.parser")
#                    article_url = "https://www.ptt.cc" + str(atag.get("href"))
                    temp = ("https://www.ptt.cc" + str(atag.get("href")), soup.title.text)
                    image_list.append(temp)
                    img_tag = soup.find_all("a")
                    for img in img_tag:
                        if ".jpg" in str(img.get("href")) or ".png" in str(img.get("href")):
                            image_list.append(str(img.get("href")))
        else:
            temp = (url, soup.title.text)
            image_list.append(temp)
            for atag in soup_list:
                image_href = str(atag.get("href"))
                if ".jpg" in image_href or ".png" in image_href:
                    image_list.append(image_href)

        return render(request, 'appPttParser/show_img.html', locals())

    return render(request, 'appPttParser/home.html', locals())

def show_img(request):

    return render(request, 'appPttParser/show_img.html')

templates/appHome/home.html
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <title>Home</title>
</head>
<body>

Home

</body>
</html>

templates/appHomePage/base.html
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

<ul style="list-style-type:none; margin:0; padding:0; ">
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appHomePage:home' %}">Home</a></li>
    {% block navbar %}{% endblock %}
</ul>
{% block content %}{% endblock %}

</body>
</html>

templates/appHomePage/home.html
{% extends "appHomePage/base.html" %}
{% block title %}Home{% endblock %}

{% block navbar %}
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appPttParser:home' %}">PttParser</a></li>
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appPrice:home' %}">Price</a></li>
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appNews:home' %}">News</a></li>
{% endblock %}

{% block content %}

<br />
<table style="margin-left:auto; margin-right:auto; margin-top:100px;" border="1">
    <tr >
        <td align="center" valign="middle">Hit to App</td>
        <td align="center" valign="middle">Introduction</td>
    </tr>
    <tr>
        <td align="center" valign="middle"><a href="{% url 'appPttParser:home' %}"><img src="https://i.imgur.com/4etGzcH.png" /></a></td>
        <td align="center" valign="middle">顯示PTT指定文章、或指定看板某一頁所有文章的圖片。</td>
    </tr>
    <tr>
        <td align="center" valign="middle"><a href="{% url 'appPrice:home' %}"><img src="https://i.imgur.com/Td9TVe7.png" /></a></td>
        <td align="center" valign="middle">輸入商品名稱，在各個網路賣場尋找價格，每個賣場最多5筆價格。</td>
    </tr>
    <tr>
        <td align="center" valign="middle"><a href="{% url 'appNews:home' %}"><img src="https://i.imgur.com/1GsKAlC.png" /></a></td>
        <td align="center" valign="middle">顯示各個新聞網站的焦點新聞。</td>
    </tr>
</table>

{% endblock %}

templates/appNews/home.html
{% extends "appHomePage/base.html" %}
{% block title %}Home{% endblock %}

{% block navbar %}
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appHomePage:home' %}">Previous</a></li>
{% endblock %}

{% block content %}

<br />
<br />
<table border="1" style="margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center" valign="middle">新聞縮圖</td>
        <td align="center" valign="middle">新聞標題</td>
        <td align="center" valign="middle">新聞來源</td>
    </tr>
{% for i in news_list %}
    <tr>
        <td align="center" valign="middle"><a href="{{ i.1 }}" target="_blank"><img src="{{ i.2 }}" /></a></td>
        <td align="center" valign="middle"><a href="{{ i.1 }}" target="_blank">{{ i.0 }}</a></td>
        <td align="center" valign="middle">{{ i.3 }}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}

templates/appPrice/home.html
{% extends "appHomePage/base.html" %}
{% block title %}Home{% endblock %}

{% block navbar %}
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appHomePage:home' %}">Previous</a></li>
{% endblock %}

{% block content %}

<br />
<form action="" method="post">
    {% csrf_token %}
    <table style="margin-left:auto; margin-right:auto; margin-top:100px;">
        <tr>
            <td><label>請輸入要比價的商品名稱</label><br /></td>
        </tr>
        <tr>
            <td>
                <input type="text" name="name" size="50">
                <input type="submit" value="確定">
            </td>
        </tr>
    </table>
</form>

{% endblock %}

templates/appPrice/result.html
{% extends "appHomePage/base.html" %}
{% block title %}Home{% endblock %}

{% block navbar %}
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appPrice:home' %}">Previous</a></li>
{% endblock %}

{% block content %}

<br />
<br />
{% if item_list %}
<table border="1" style="margin-left:auto; margin-right:auto;">
    <tr>
      <td align="center" valign="middle">商品圖</td>
      <td align="center" valign="middle">商品名稱</td>
      <td align="center" valign="middle">販售平台</td>
      <td align="center" valign="middle">價格</td>
    </tr>
{% else %}
    {{ item_name }} 查無此商品！
{% endif %}
{% for item in item_list %}
    <tr>
        <td align="center" valign="middle"><img src="{{ item.3 }}" width="50%"></td>
        <td align="center" valign="middle"><a href="{{ item.1 }}" target="_blank">{{ item.0 }}</a></td>
        <td align="center" valign="middle">{{ item.4 }}</td>
        <td align="center" valign="middle">{{ item.2 }}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}

templates/appPttParser/home.html
{% extends "appHomePage/base.html" %}
{% block title %}Home{% endblock %}

{% block navbar %}
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appHomePage:home' %}">Previous</a></li>
{% endblock %}

{% block content %}

<br />
<form action="" method="post">
    {% csrf_token %}
    <table style="margin-left:auto; margin-right:auto; margin-top:100px;">
        <tr>
            <td>
                <label>請輸入要顯示圖片的PTT文章網址或看板名稱<br />
                Ex: Beauty、https://www.ptt.cc/bbs/Beauty/index.html、https://www.ptt.cc/bbs/Beauty/M.1501121300.A.484.html</label><br />
                <br />
            </td>
        </tr>
        <tr>
            <td>
                <input type="text" name="href" size="100">
                <input type="submit" value="確定">
            </td>
        </tr>
        {% if message != "" %}
        <tr>
            <td>{{ message }}</td>
        </tr>
        {% endif %}
    </table>

</form>

{% endblock %}

templates/appPttParser/show_img.html
{% extends "appHomePage/base.html" %}
{% block title %}Home{% endblock %}

{% block navbar %}
    <li style="float:left; display:inline-block; padding:10px; "><a href="{% url 'appPttParser:home' %}">Previous</a></li>
{% endblock %}

{% block content %}

<br />
{% for image in image_list %}
    {% if ".jpg" in image or ".png" in image %}
        <img src="{{ image }}" width='20%'>
    {% else %}
        <br />
        <br />
        <br />
        <br />
        <a href="{{ image.0 }}" target="_blank">{{ image.1 }}</a><br />
    {% endif %}
{% endfor %}

{% endblock %}